name: flutter_address_input
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  cloud_firestore: ^4.13.2
  dio: ^5.4.0
  firebase_core: ^2.23.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  hooks_riverpod: ^2.4.8
  http: ^1.1.0
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  retrofit: ^4.0.3
  riverpod_annotation: ^2.3.3

dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.4
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true
